### ISSUE TITLE
Can't make a round button

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-button#76]
The simple code to get a rounded button:

```css
:host {
  width: var(--lumo-size-xl);
  height: var(--lumo-size-xl);
}
```

Live demo: https://jsfiddle.net/6r5htd05/157/

**Given**: the root font-size is 16px;

**Expected**: the button size is `56x56px` (`16px * 3.5 = 56px`)

**Actual**: the button size is `72x56px`:

![](https://i.imgur.com/ry9fZic.png)
